version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    depends_on:
      - db
    expose:
      - "8000"                # только во внутренней сети compose

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"               # наружу отдаёт только nginx
    volumes:
      - ./nginx.api.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db-data:
