services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      # читаем полную строку подключения из .env
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db-data:
